### PR TITLE
Courtney

### PR DESCRIPTION
**Pull request by clburns107**

### CODE REVIEW

**Comment by sumeetjain** [comment]
:+1:

**Comment by sumeetjain** [comment]
:+1:

**Comment by halfghaninne** [comment]
Which method is throwing the error and at which line?

**Comment by clburns107** [comment]
the .each method is throwing the error. on line 13 of the dashboard.erb

**Comment by clburns107** [comment]
I expected to see the dashboard when using this redirect on my todos controller but im seeing a sinatra doesnt know this ditty page.

**Comment by sumeetjain** [comment]
`redirect "/todos/dashboard"` creates a `get` request for `"/todos/dashboard"`. The first thing that happens when a request is made is that Sinatra finds a matching controller action. If you get the "doesn't know this ditty" error, it's because Sinatra cannot find a matching controller action.

Please reply with the full Ruby code of the controller action that matches a `get` request for `"/todos/dashboard"`.

**Comment by clburns107** [comment]
MyApp.get "/dashboard" do
  @current_user = User.find_by_id(session["user_id"])
  if @current_user != nil 
    @user_tasks = Todo.where(user_id: session["user_id"])
    erb :"todos/dashboard"
  else
    erb :"logins/login_error"
  end
end

Oh i see. I'm matching the erb view file path instead of the get request path. it works now :)

**Comment by sumeetjain** [comment]
:)

**Comment by clburns107** [comment]
All features functional.  See commit. 

To previous question: A creator is not necessarily always an assignor.  You as the creator will be the assignor when a task is originally created, but if the assignee reassigns the task they now become the assignor while you remain the creator...

**Comment by sumeetjain** [comment]
Gotcha–I understand now.

**Comment by clburns107** [comment]
So im thinking that to be able to assign 1 todo object to multiple users you would have to have a collection of data inside of one record (the user_id column). Sooooo....

Can you enter multiple values into 1 record? if the record took an  integer how would i separate them?

**Comment by sumeetjain** [comment]
You will need a "bridge table", like how swimmers/events are connected by 'signups'.

(Let me know if this is too little clarification.)

**Comment by clburns107** [comment]
oooooh ok that makes more sense. :)

**Pull request closed without merging**
